baseurl = "https://joshuaulrich.github.io/fosstrading/"
title = "FOSS Trading"
languageCode = "en-us"
publishDir = "docs"

theme = [ "mainroad" ]
paginate = "10" # Number of posts per page

disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "disclosures"
    name = "Disclosures"
    url  = "page/disclosures/"
    weight = 2

[[menu.main]]
    identifier = "enterprise"
    name = "For Enterprise"
    url  = "page/enterprise/"
    weight = 3

[Permalinks]
    post = ":year/:month/:filename/"

[Author]
  name = "Joshua Ulrich"
  bio = ""
#  avatar = "img/avatar.png"

[Params]
  subtitle = "Algorithmic Trading with Free Open Source Software"
#  description = "John Doe's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information

# mainroad theme
  highlightColor = '#5282d1'
  customCSS = [ "fosstrading.css" ]

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "csi-banner", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
