baseurl = "https://blog.fosstrading.com/"
title = "FOSS Trading"
languageCode = "en-us"
publishDir = "docs"

theme = [ "mainroad" ]
paginate = "10" # Number of posts per page

disqusShortname = "foss-trading"  # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-3314405-2"  # Enable Google Analytics by entering your tracking id

# code highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
## and make sure javascript highlighting is off
useHLJS = false

uglyURLs = true
disablePathToLower = true

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "disclosures"
    name = "Disclosures"
    url  = "/page/disclosures/"
    weight = 2

[[menu.main]]
    identifier = "enterprise"
    name = "For Enterprise"
    url  = "/page/enterprise/"
    weight = 3

[Permalinks]
    post = ":year/:month/:filename/"
    tags = "search/label/:title"

[Author]
  name = "Joshua Ulrich"
  bio = ""
#  avatar = "img/avatar.png"

[Params]
  subtitle = "Algorithmic Trading with Free Open Source Software"
#  description = "John Doe's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = false
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information

# mainroad theme
  highlightColor = '#5282d1'
  customCSS = [ "fosstrading.css", "syntax.css" ]

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "email-form", "csi-banner", "recent", "taglist", "adsense-sidebar" ]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
